---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: "hacbs-signing-pipeline"
    app: "hacbs-signing-pipeline"
    env: production
    paas.redhat.com/appcode: RSIG-001
  name: "hacbs-signing-pipeline-config-redhatrelease2"
data:
  PYXIS_URL: "https://pyxis.engineering.redhat.com"
  SIG_KEY_ID: "4096R/FD431D51 SHA-256"
  SIG_KEY_NAME: "redhatrelease2"
  PYXIS_SSL_CERT_FILE_NAME: "hacbs-signing-pipeline.pem"
  PYXIS_SSL_CERT_SECRET_NAME: "hacbs-signing-pipeline-certs"
  PYXIS_SSL_KEY_FILE_NAME: "hacbs-signing-pipeline.key"
  UMB_SSL_CERT_FILE_NAME: "hacbs-signing-pipeline.pem"
  UMB_SSL_CERT_SECRET_NAME: "hacbs-signing-pipeline-certs"
  UMB_SSL_KEY_FILE_NAME: "hacbs-signing-pipeline.key"
  UMB_CLIENT_NAME: "hacbs-signing-pipeline"
  UMB_URL: "umb.api.redhat.com"
  UMB_LISTEN_TOPIC: VirtualTopic.eng.robosignatory.hacbs.sign
  UMB_PUBLISH_TOPIC: VirtualTopic.eng.hacbs-signing-pipeline.hacbs.sign
