apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: internal-services
    app.kubernetes.io/part-of: internal-services
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: stonesoup-int-srvc
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-service-account
  namespace: stonesoup-int-srvc
secrets:
- name: redhat-workloads-token
