name: JIRA CI - Test Promotion Action

on:
  workflow_dispatch:
    inputs:
      promotion-type:
        description: The type of promotion to perform
        type: choice
        required: true
        default: development-to-staging
        options:
          - development-to-staging
          - staging-to-production
      dry-run:
        description: |
          Dry run: Print out the changes that would be promoted but do not perform the git push
        type: boolean
        required: true
        default: false

permissions:
  contents: read

jobs:
  test-jira-ci:
    runs-on: ubuntu-latest
    outputs:
      parsed_tickets_file: ${{ steps.promote.outputs.parsed_tickets_file }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Generate parsed-tickets.json
        id: promote
        run: |
          ./.github/scripts/test.sh


      - name: Show file (sanity check)
        run: |
          echo "=== parsed-tickets.json ==="
          cat ${{ steps.promote.outputs.parsed_tickets_file }}
          echo "==========================="

      - name: Run JIRA CI Action
        if: |
          steps.promote.outputs.parsed_tickets_file != ''
        uses: konflux-ci/release-service-automations/jira-ci@2a074bf7270b4212038f4f8e06dff76b8760254b
        with:
          jira_url: "https://issues.redhat.com"
          promotion_type: ${{ inputs.promotion-type }}
          metadata_file: ${{ steps.promote.outputs.parsed_tickets_file }}
          jira_token: ${{ secrets.JIRA_TOKEN }}
          dry_run: ${{ inputs.dry-run }}
